### ISSUE TITLE
publish-test-results don't accept --baseFolder

### ISSUE THREAD

**Issue by HenrikSommer-Energinet** [specsolutions/specsync-for-tfs-documentation#3]
I have this folder and files:
```
C:\temp\Config
C:\temp\TestResult
C:\temp\dotnet-tools.json
C:\temp\Config\specsync.json
C:\temp\Config\specsync.lic
C:\temp\TestResult\testresult.trx
```
If i run this from powershell:
`PS C:\Temp> dotnet specsync publish-test-results --testConfiguration "#123" --testResultFile "C:\Temp\TestResult\testresult.trx" --user $userDev --baseFolder "C:\Temp\Config"`

I get this result:
```
SpecSync4AzureDevOps v3.0.2
Copyright © 2016-2020 Spec Solutions

ERROR: The specified config file 'C:\Temp\specsync.json' does not exist. To create a new config file, use the 'init' command (e.g. 'dotnet specsync init' or 'SpecSync4AzureDevOps.exe init').
  use --verbose option for detailed exception stack trace
```

Is --baseFolder  not suppose to tell that it can find specsync.json here: C:\temp\Config\specsync.json or do I miss something?

**Comment by gasparnagy** [comment]
Based on the current specification, the base folder is used for finding the "[project, feature and license files](https://specsolutions.gitbook.io/specsync/reference/command-line-reference)" and it is not used to find the configuration file. As you have named your folder `Config`, I assume that it will not contain the feature files or the project files (if you use SpecFlow). Basically the `--baseFolder` is to set the main root folder of your BDD feature-set (project). In this regards it is behaving similarly to changing the working folder and run the synchronization tool from there. (Although I admit that in this case it would be more logical if the config file path would also use that...)

To be able to use the config file from your `Config` folder, you would need to specify it explicitly (also for the license):

```
PS C:\Temp> dotnet specsync publish-test-results --testConfiguration "#123" --testResultFile "C:\Temp\TestResult\testresult.trx" --user $userDev --license Config\specsync.lic Config\specsync.json
```

If the license file is always in the same folder as the config file, you can also specify the license file location in the config file with:

```
"toolSettings": {
  "licensePath": "specsync.lic" // in the same folder as the config file itself
},
```

In this case you only need to specify the config file:

```
PS C:\Temp> dotnet specsync publish-test-results --testConfiguration "#123" --testResultFile "C:\Temp\TestResult\testresult.trx" --user $userDev Config\specsync.json
```

You can also consider storing your license file in a user-specific location, see https://specsolutions.gitbook.io/specsync/features/general-features/hierarchical-configuration-files#user-specific-configuration-files for details.

PS: I will review the documentation of the `--baseFolder` and see if this could be better clarified. I think the `--baseFolder` can even be removed in its current form, because it is more straightforward and less confusing...
