### ISSUE TITLE
Would be nice to get if it is possible to publish automated test results to Release Tests tab

### ISSUE THREAD

**Issue by andrei-ts** [specsolutions/specsync-for-tfs-documentation#7]
Current documentation contains only the information how to publish test results to Build pipeline.

for https://specsolutions.gitbook.io/specsync/reference/command-line-reference/publish-test-results-command
 you can specify buildId or buildNumber but nothing about Release related parameters.

Here is the use case. I have web ui test automation for Specflow.
I build solution with build pipeline. It has buildId=1
After that I create the following release with ReleaseId=1 which do the following

- deploy app to QA Environment
Then run 2 testing stages:
- Run Chrome Tests from above build pipeline
- Run Edge Tests from above build pipeline

Is it possible to configure specsync publish-test-results to publish automated tests results to both "Run Chrome Tests from above build pipeline" and "Run Edge Tests from above build pipeline" stages so they would be appeared in Tests tab of those stages.

**Comment by gasparnagy** [comment]
This should work by default without specifying the build id manually (SpecSync reads out the build/stage references from environment variables). Please make sure you use v3.2.4 or later because it has been fixed there (see https://specsolutions.gitbook.io/specsync/changelog#v-3-2-4-2021-05-21). 

If you still experience the problem, please follow up on email and we should make an online call to figure out what is wrong. (I am closing this issue for now.)
